server:
    port: 1020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
     application:
             name: API-Gateway


zuul:
 prefix: /api
 routes:
    Producer:
      path: /producers/**
      #url: http://localhost:4040
      serviceId: PRODUCER
    JPA:
       path: /jpa/**
       #url: http://localhost:9090
       serviceId: JPA
logging:
      level:
           root: ERROR
       
       